name: sync

on:
  schedule:
    - cron: "0 * * * *"   # hourlly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/The-Powder-Toy/The-Powder-Toy.git || true
          git fetch upstream

      - name: Force sync upstream-master
        run: |
          git checkout -B upstream-master upstream/master
          git push origin upstream-master --force